<a href="https://colab.research.google.com/github/Timansamal046/Real-Estate-Analysys/blob/main/house_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.set_option("display.max_rows" , None)
pd.set_option("display.max_columns" , None)

In [ ]:
df = pd.read_csv("/content/houses.csv")

In [ ]:
df.sample(10)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
43,16 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/16-bhk-bedroom-indepen...,NaN,13.5 Crore,"₹ 50,000/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),16 Bedrooms,16 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","C Block, Sushant Lok Phase 1, Gurgaon, Haryana",4 Floors,North-West,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...",Brand new building floor wise with stilt and l...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",D69611236
147,1 Bedroom House for sale in Laxman Vihar Phase 2,https://www.99acres.com/1-bhk-bedroom-independ...,NaN,65 Lac,"₹ 92,857/sq.ft.",(7 sq.m.) Plot Area,Plot area 70(6.5 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,Others,"Laxman Vihar Phase 2, Gurgaon, Haryana",1 Floors,South-East,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Near by sec 4 near by market near by hospital\...,"['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...","['Water Storage', 'Visitor Parking', 'Rain Wat...",NaN,A69481490
48,4 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Bptp Visionnaire,5.4 Crore,"₹ 20,690/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room,Servant Room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3 Floors,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",H68309874
610,5 Bedroom House for sale in Mianwali Colony,https://www.99acres.com/5-bhk-bedroom-independ...,Project Mianwali Colony,2 Crore,"₹ 14,815/sq.ft.",(125 sq.m.) Built-up Area,Built Up area: 1350 (125.42 sq.m.),5 Bedrooms,5 Bathrooms,2 Balconies,NaN,"Mianwali Colony, Near Bus Stand, Gurgaon, Hary...",3 Floors,East,undefined,"['Hanuman Mandir', 'Sheetla Mata Mandir', 'Lal...","5 bath, semi-Furnished, ground floor (Of 3), o...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of...",P65742804
408,3 Bedroom House for sale in Rajendra Park,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,1.3 Crore,"₹ 11,556/sq.ft.",(105 sq.m.) Built-up Area,Built Up area: 1125 (104.52 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,NaN,"Rajendra Park Block G, Sector 105, Rajendra Pa...",1 Floors,East,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Best in class property available at rajendra p...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",E68592468
804,4 Bedroom House for sale in Sector 42 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Central Park,6.5 Crore,"₹ 19,607/sq.ft.",(308 sq.m.) Plot Area,Plot area 3315(307.97 sq.m.),4 Bedrooms,5 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room","222, Sector 42 Gurgaon, Gurgaon, Haryana",1 Floors,North-East,5 to 10 Year Old,"['Sector 42-43 metro station', 'Sector 53-54 m...",It is 4bhk villa in central park 1with moduler...,"['4 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geys...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN,U69241434
458,9 Bedroom House for sale in Rattan Garden,https://www.99acres.com/9-bhk-bedroom-independ...,Rattan Garden,1.1 Crore,"₹ 8,730/sq.ft.",(117 sq.m.) Plot Area,Plot area 140(117.06 sq.m.),9 Bedrooms,3 Bathrooms,3 Balconies,NaN,"431, Rattan Garden, Gurgaon, Haryana",3 Floors,NaN,10+ Year Old,"['Chintapurni Mandir', 'Ravi Clinic and Health...",Old construction.....Ready to live - 9 rooms ....,NaN,['Visitor Parking'],"['Environment3 out of 5', 'Lifestyle4 out of 5...",M68298578
941,4 Bedroom House for sale in Sector 26 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,DLF City Phase 1,5.5 Crore,"₹ 30,556/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Store Room","G Block, Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",This is a old built-Up duplex house similar to...,"['3 Wardrobe', '5 Fan', '4 Geyser', '20 Light'...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN,U69483020
589,5 Bedroom House for sale in Dwarka Expressway ...,https://www.99acres.com/5-bhk-bedroom-independ...,rattan vihar rajendra park,85 Lac,"₹ 14,166/sq.ft.",(56 sq.m.) Plot Area,Plot area 600(55.74 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,NaN,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",4 Floors,NaN,0 to 1 Year Old,"['Shri Multispeciality Hospital', 'Esic Hospit...",Looking for buyer to purchase our house/villa ...,[],NaN,NaN,T66532438
328,4 Bedroom House for sale in Arjun Nagar,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,1.6 Crore,"₹ 28,674/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),4 Bedrooms,6 Bathrooms,1 Balcony,NaN,"Arjun Nagar, Gurgaon, Haryana",3 Floors,NaN,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",W69287014

In [ ]:
df.shape

(1044, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [ ]:
df.isnull().sum()

property_name        0
link                 0
society            591
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     455
address             13
noOfFloor           77
facing             370
agePossession       57
nearbyLocations    131
description          8
furnishDetails     301
features           370
rating             137
property_id          8
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(13)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(1031, 21)

In [ ]:
df.head(10)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272
5,20 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/20-bhk-bedroom-indepen...,NaN,4.5 Crore,"₹ 39,062/sq.ft.",(107 sq.m.) Plot Area,Plot area 128(107.02 sq.m.),20 Bedrooms,20 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",4 Floors,East,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...",Best for investment purpose. 3l rupees monthly...,"['1 Water Purifier', '1 Fridge', '20 Fan', '1 ...","['Water Storage', 'Park', 'Visitor Parking', '...","['Environment5 out of 5', 'Lifestyle5 out of 5...",V69218808
6,5 Bedroom House for sale in Sector 66 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,12 Crore,"₹ 37,037/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room,Store Room","Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Available for sale 5bhk independent house in e...,"['4 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Lifestyle4 out of 5...",G55931988
7,16 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/16-bhk-bedroom-indepen...,Luxury DLF City Floors,20 Crore,"₹ 48,889/sq.ft.",(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),16 Bedrooms,16 Bathrooms,3+ Balconies,Servant Room,"DLF Phase 1, Gurgaon, Haryana",4 Floors,NaN,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",Prime location on dlf phase - 1 builder floor ...,"['16 Wardrobe', '26 Fan', '1 Exhaust Fan', '16...","['High Ceiling Height', 'Park', 'Visitor Parki...","['Environment5 out of 5', 'Lifestyle5 out of 5...",E67952012
8,6 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,10.85 Crore,"₹ 38,150/sq.ft.",(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6 Bedrooms,6 Bathrooms,1 Balcony,Store Room,"DLF Phase 2, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...","6 bhk kothi in dlf phase 2, gurgaon available ...","['4 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5...",U69218678
9,3 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/3-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,1.95 Crore,"₹ 10,077/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"C Block Small Nos, Sushant Lok Phase 1, Gurgao...",4 Floors,West,0 to 1 Year Old,"['Huda city centre metro station', 'Sector 42-...",Brand new builder floor at very reasonable pri...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Lifestyle5 out of 5...",L69688060

In [ ]:
df.drop(columns = ["property_id","link"],inplace = True)

In [ ]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df.rename(columns = {"rate":"price_per_sqft"},inplace = True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df["society"].value_counts()

society
Emaar MGF Marbella                                   26
International City by SOBHA Phase 2                  26
Vipul Tatvam Villa                                   24
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             13
Unitech Espace                                       11
DLF City Plots Phase 2                               11
DLF City Plots                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Not Applicable                                        7
Uppal Southend4.0 ★                                   7
Ansals Palam Vihar                                    6
Sushant Lok 1 Builder Floors                          6
Experion Windchants3.8 ★                              5
DLF City Phase 1                                      5
Ansal Sushant Lok Plots4.1 ★                          4
Unitech Aspen Greens                                  4
DLF Alameda                                           4
Vatika India Next4.1 ★                                4
nul                                                   4
Puri Diplomatic Greens4.0 ★                           3
DLF City Plots Phase 3                                3
Anant Raj Estates                                     3
Central Park Flower Valley                            3
Housing Board Colony                                  3
SS Aaron Ville                                        3
Vatika Signature Villas                               3
Eros Rosewood Villas                                  3
BPTP Astaire Gardens3.7 ★                             3
Unitech Nirvana Birch Court                           3
Ansals Florence Villa                                 3
Eros Rosewood City4.0 ★                               3
Malibu Towne                                          3
Palam Vihar Extension West Zone RWA                   3
DLF New Town Heights 24.0 ★                           3
Rattan Garden                                         3
Sector 14 RWA                                         3
Tata Primanti4.1 ★                                    3
Unitech Deerwood Chase                                2
shivpuri                                              2
Project Housing Board Colony                          2
Project Mianwali Colony                               2
Bestech Park View Ananda4.2 ★                         2
Spaze Privy3.9 ★                                      2
Emaar Emerald Hills4.1 ★                              2
Suncity Essel Towers4.2 ★                             2
Ansal API Esencia3.7 ★                                2
Luxury DLF City Floors                                2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Emaar The Palm Springs                                2
Suncity Township4.1 ★                                 2
Nirvana Cedar Crest                                   2
SS Hibiscus                                           2
Silverglades Tarudhan Valley Golf Resort              2
Ardee City3.8 ★                                       2
Hans Enclave                                          2
Satya The Hermitage3.5 ★                              2
Sobha City                                            2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sector 38 RWA                                         2
Unitech Escape3.8 ★                                   2
ATS Tourmaline3.9 ★                                   1
house number B-34                                     1
Rajendra Park Gurgaon                                 1
DLF Gardencity Enclave                                1
Surat nagar phase 2                                   1
My Home                                               1
Signature Global Park4.0 ★                            1
Sector-17C                                            1
huda sector-56 gurgaon                                1
private house                                         1
Grover Homes Sec 4                                    1
sector 37                                             1
FLOOR WISE DESIGNER KOTHI                             1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
Ansal Heights3.2 ★                                    1
Ninex City                                            1
rajendra park sec 105                                 1
HUDA Ashok Vihar Phase 13.9 ★                         1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Prem Kunj                                             1
secter 16a daultabad faridabad house no 313           1
Bhawani enclave                                       1
Ansal Celebrity Homes                                 1
Shri Shyam Residency                                  1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Laxmi Garden Sector-11                                1
ROW HOUSE                                             1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Krishna Palace                                        1
Huda Flats                                            1
Naman Residency                                       1
Madan puri                                            1
Smart World Gems                                      1
Tulip Ivory3.5 ★                                      1
MANOHAR NAGAR                                         1
Vatika Sovereign Next                                 1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
RK Excelo                                             1
Anand Garden, Sector-105                              1
Jacobpura Gurugram                                    1
Hero Homes                                            1
Ganpati Heights Apartment                             1
Huda Plots                                            1
DLF Garden City Floors                                1
Emaar MGF The Palm Drive4.1 ★                         1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
DLF The Arbour                                        1
Om Nagar, Sector-11                                   1
Suncity Avenue 76                                     1
SS Omnia                                              1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
Greenopolis                                           1
Vipul World3.9 ★                                      1
Nirmal Enclave, Maruti Kunj Road                      1
Ansal Esencia Sovereign Floors                        1
Raj Villas                                            1
Shivaji Nagar Residential                             1
jacob pura                                            1
mahavir pura                                          1
Bhim Nagar Society                                    1
Sai Kripa Floors 5                                    1
DLF City Plot Phase 4                                 1
Signature Global City 92                              1
mian wali                                             1
HUDA Plot Sector 38                                   1
nirvana country                                       1
Landmark House                                        1
Nitin Vihar                                           1
Sector 15 Part 2 RWA                                  1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Ashok vihar phase III Extension                       1
Ansal                                                 1
Adani Brahma Samsara4.2 ★                             1
Sheetla Enclave                                       1
DLF City Plot Phase 3                                 1
Signature Global City 63A                             1
rattan vihar rajendra park                            1
sneh vihar                                            1
Unitech South City 23.8 ★                             1
Smart World Orchard                                   1
Ansal Florence Super                                  1
Ireo Victory Valley4.1 ★                              1
Ansal API Spanish Court                               1
4S Aradhya Homes                                      1
Birla Navya                                           1
Central Park Flower Valley Cerise Floors              1
DLF City Plots Phase 4                                1
Kothi                                                 1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City                                 1
DLF Floors Phase 3                                    1
Ansal Sushant Residency                               1
DLF South City 1                                      1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
Vatika The Seven Lamps3.8 ★                           1
Unitech Greenwood City3.6 ★                           1
Nirvana Country                                       1
Signature Global City 81                              1
Satya The Legend3.8 ★                                 1
DLF Pink Town House4.0 ★                              1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
The Laburnum                                          1
Ansal Sushant Lok 2                                   1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Huda                                                  1
Huda Floor                                            1
Name: count, dtype: int64

In [ ]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [ ]:
df['society'].value_counts().shape

(183,)

In [ ]:
df['society'] = df['society'].str.replace('nan','independent')

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
# price
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
4.5 Crore           13
5 Crore             13
8 Crore             13
50 Lac              13
75 Lac              13
70 Lac              13
7 Crore             12
8.5 Crore           12
85 Lac              12
1.5 Crore           11
4 Crore             11
90 Lac              10
Price on Request    10
2.25 Crore          10
45 Lac              10
60 Lac              10
10 Crore            10
2.5 Crore           10
9 Crore             10
12 Crore             9
2 Crore              9
80 Lac               9
9.5 Crore            9
1.1 Crore            9
1.7 Crore            9
1 Crore              8
1.6 Crore            8
11 Crore             8
6.75 Crore           8
4.6 Crore            8
3.75 Crore           7
1.2 Crore            7
55 Lac               7
40 Lac               7
1.3 Crore            7
12.5 Crore           7
95 Lac               7
65 Lac               7
1.35 Crore           7
2.1 Crore            7
7.5 Crore            6
6.25 Crore           6
3.25 Crore           6
2.95 Crore           6
10.5 Crore           6
13.5 Crore           6
3.6 Crore            6
2.75 Crore           6
1.45 Crore           6
5.7 Crore            6
4.25 Crore           6
1.15 Crore           6
16 Crore             6
15 Crore             5
3 Crore              5
1.25 Crore           5
5.6 Crore            5
38 Lac               5
4.75 Crore           5
7.25 Crore           5
35 Lac               5
2.8 Crore            5
1.8 Crore            5
18 Crore             4
13 Crore             4
4.35 Crore           4
17 Crore             4
3.3 Crore            4
5.8 Crore            4
9.25 Crore           4
1.4 Crore            4
1.65 Crore           4
3.2 Crore            4
5.75 Crore           4
37 Lac               4
4.7 Crore            4
11.5 Crore           4
6.8 Crore            4
2.4 Crore            4
42 Lac               4
8.25 Crore           4
5.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
62 Lac               3
5.65 Crore           3
82 Lac               3
2.2 Crore            3
6.95 Crore           3
3.85 Crore           3
1.55 Crore           3
2.3 Crore            3
3.1 Crore            3
1.85 Crore           3
92 Lac               3
5.15 Crore           3
32 Lac               3
34 Lac               3
49 Lac               3
1.16 Crore           3
7.35 Crore           3
2.9 Crore            3
3.4 Crore            3
1.9 Crore            3
4.3 Crore            3
8.4 Crore            3
7.2 Crore            3
19 Crore             3
6.4 Crore            3
11.95 Crore          2
1.05 Crore           2
14 Crore             2
11.25 Crore          2
6.3 Crore            2
30 Lac               2
10.45 Crore          2
66 Lac               2
36 Lac               2
26 Crore             2
11.75 Crore          2
8.49 Crore           2
2.55 Crore           2
3.55 Crore           2
3.15 Crore           2
9.9 Crore            2
15.5 Crore           2
58.25 Lac            2
2.15 Crore           2
67 Lac               2
3.05 Crore           2
1.75 Crore           2
48 Lac               2
10.85 Crore          2
7.1 Crore            2
58 Lac               2
4.95 Crore           2
19.5 Crore           2
3.65 Crore           2
10.55 Crore          2
3.35 Crore           2
89 Lac               2
3.51 Crore           2
6.6 Crore            1
6.2 Crore            1
5.9 Crore            1
8.8 Crore            1
1.87 Crore           1
4.12 Crore           1
5.35 Crore           1
5.85 Crore           1
7.05 Crore           1
2.68 Crore           1
2.7 Crore            1
10.75 Crore          1
61 Lac               1
18.25 Crore          1
2.35 Crore           1
8.6 Crore            1
9.55 Crore           1
9.8 Crore            1
4.99 Crore           1
9.85 Crore           1
1.18 Crore           1
9.01 Crore           1
15.1 Crore           1
1.04 Crore           1
25 Crore             1
8.7 Crore            1
15.5 Lac             1
12.39 Crore          1
7.49 Crore           1
55.11 Lac            1
68 Lac               1
4.65 Crore           1
6.1 Crore            1
1.72 Crore           1
52 Lac               1
78 Lac               1
1.52 Crore           1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
7.69 Crore           1
22 Lac               1
7.5 Lac              1
3.12 Crore           1
11.3 Crore           1
3.69 Crore           1
4.02 Crore           1
3.93 Crore           1
29 Lac               1
3.08 Crore           1
18 Lac               1
24 Lac               1
98 Lac               1
83 Lac               1
7.99 Crore           1
5.4 Crore            1
65.8 Lac             1
18.02 Crore          1
96 Lac               1
13 Lac               1
69 Lac               1
2.43 Crore           1
74 Lac               1
3.09 Crore           1
44 Lac               1
47.5 Lac             1
59 Lac               1
1.39 Crore           1
3.87 Crore           1
2.6 Crore            1
1.34 Crore           1
46 Lac               1
9.54 Crore           1
14.75 Crore          1
8.1 Crore            1
27 Lac               1
24 Crore             1
7.46 Crore           1
17.3 Crore           1
18.9 Crore           1
47 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
1.07 Crore           1
5.2 Crore            1
42.75 Lac            1
22 Crore             1
4.15 Crore           1
8.9 Crore            1
4.49 Crore           1
8.81 Crore           1
6.81 Crore           1
59.95 Lac            1
3.99 Crore           1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
5.1 Crore            1
5.46 Crore           1
10.56 Crore          1
2.01 Crore           1
3.9 Crore            1
5.88 Crore           1
52.75 Lac            1
12.25 Crore          1
46.75 Lac            1
9.4 Crore            1
10.3 Crore           1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
7.3 Crore            1
7.6 Crore            1
2.65 Crore           1
99 Lac               1
11.29 Crore          1
1.27 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
4.31 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
5.51 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [ ]:
df = df[df['price'] != 'Price on Request']

In [ ]:
df.sample(10)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
636,2 Bedroom House for sale in Ashok Vihar Phase ...,independent,70 Lac,"₹ 7,007/sq.ft.",(93 sq.m.) Plot Area,Plot area 111(92.81 sq.m.),2 Bedrooms,3 Bathrooms,1 Balcony,"Pooja Room,Store Room","G1 Block , House No 49, Ashok Vihar Phase 3 Ex...",1 Floors,North,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Spacious room, proper ventilation, beautiful t...",NaN,"['Water purifier', 'Water Storage', 'Park', 'I...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
698,4 Bedroom House for sale in Palam Vihar,ansal api spanish court,2.9 Crore,"₹ 18,626/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.)Built Up area: 1415...,4 Bedrooms,4 Bathrooms,3 Balconies,Store Room,"A, Block Ansals Palam Vihar, Palam Vihar, Gurg...",2 Floors,North,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",On sale 173 sq yrds built up house park facing...,"['4 Wardrobe', '10 Fan', '1 Exhaust Fan', '2 G...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
578,5 Bedroom House for sale in Sohna Road,sneh vihar,1.35 Crore,"₹ 10,000/sq.ft.",(125 sq.m.) Plot Area,Plot area 1350(125.42 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,NaN,"Sohna Road, Gurgaon, Haryana",4 Floors,NaN,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...",We are proud owners of house/villa available f...,[],NaN,NaN
913,3 Bedroom House for sale in Nirvana Country,unitech nirvana birch court,7.1 Crore,"₹ 283,333/sq.ft.",(22 sq.m.) Plot Area,Plot area 240(22.3 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"Nirvana Country, Gurgaon, Haryana",1 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",It is good livable house with 100 power backup...,"['1 Modular Kitchen', '3 Wardrobe', 'No AC', '...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
223,3 Bedroom House for sale in New Palam Vihar Ph...,independent,95 Lac,"₹ 10,555/sq.ft.",(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.),3 Bedrooms,2 Bathrooms,2 Balconies,Store Room,"New Palam Vihar Phase 1, Gurgaon, Haryana",3 Floors,South-East,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Near mahindra aura sector - 110 main bajghera ...,NaN,"['Park', 'Fitness Centre / GYM']",NaN
985,5 Bedroom House for sale in Sector 14 Gurgaon,independent,5.5 Crore,"₹ 16,975/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.)Built Up area: 355 ...,5 Bedrooms,4 Bathrooms,2 Balconies,Study Room,"00001425, Sector 14 Gurgaon, Gurgaon, Haryana",2 Floors,East,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",House for sale plot size 360 sqyard plot rate ...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."
508,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,10 Crore,"₹ 181,818/sq.ft.",(51 sq.m.) Plot Area,Plot area 550(51.1 sq.m.),5 Bedrooms,6 Bathrooms,3 Balconies,"Study Room,Servant Room","Sector 33 Gurgaon, Gurgaon, Haryana",4 Floors,North-East,0 to 1 Year Old,"['Rajiv Chowk Mosque', 'Airforce Hospital', 'S...",It is a corner and east facing villa. The poss...,NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
652,9 Bedroom House for sale in Palam Vihar,independent,3.65 Crore,"₹ 23,442/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,"Pooja Room,Servant Room","Palam Vihar, Gurgaon, Haryana",3 Floors,West,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Nice kuxury indipendent house,close to delhi,c...","['1 Water Purifier', '18 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
981,5 Bedroom House for sale in DLF Phase 2,independent,10 Crore,"₹ 37,037/sq.ft.",(251 sq.m.) Plot Area,Plot area 2700(250.84 sq.m.)Built Up area: 950...,5 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Servant Room","M Block Corner, DLF Phase 2, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['Mg road metro station', 'Vodafone belvedere ...",This is corner unit near to highway five bedro...,"['1 Water Purifier', '7 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
633,3 Bedroom House for sale in Sohna Road,independent,5.5 Crore,"₹ 5,093/sq.ft.",(1003 sq.m.) Plot Area,Plot area 1200(1003.35 sq.m.)Built Up area: 35...,3 Bedrooms,3 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","Sector 63a, Sohna Road, Gurgaon, Haryana",2 Floors,West,5 to 10 Year Old,"['Kamal Hospital and Maternity Centre', 'Gobin...",Three bedroom villa in the most serene area. W...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN

In [ ]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [ ]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

<ipython-input-51-45c08249b2fd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].str.split(' ').apply(treat_price)

In [ ]:
df['price'].sample(10)

43      13.5
628      2.9
120      7.0
627      1.6
231      8.0
673     22.0
388      0.6
1010     9.5
85       NaN
981     10.0
Name: price, dtype: float64

In [ ]:
# price_per_sqft
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     14
₹ 33,333/sq.ft.     11
₹ 11,111/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 13,333/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 11,100/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 23,333/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 5,000/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 9,444/sq.ft.       5
₹ 34,722/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 18,889/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 35,000/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 20,000/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 12,222/sq.ft.      3
₹ 60,000/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 13,889/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 6,666/sq.ft.       3
₹ 29,880/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 36,111/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 50,000/sq.ft.      3
₹ 32,222/sq.ft.      3
₹ 7,500/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 24,845/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 4,444/sq.ft.       2
₹ 38,194/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 24,155/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 17,037/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 21,759/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 9,000/sq.ft.       2
₹ 38,760/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 100,000/sq.ft.     2
₹ 12,342/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 13,910/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 8,888/sq.ft.       2
₹ 19,708/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 16,975/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 17,778/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 44,444/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 84,000/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 18,888/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 13,501/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 22,812/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 400,000/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 27,461/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 8,101/sq.ft.       1
₹ 2,716/sq.ft.       1
₹ 40,850/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 9,210/sq.ft.       1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 7,333/sq.ft.       1
₹ 31,686/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 17,662/sq.ft.      1
₹ 10,582/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 14,166/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 194,444/sq.ft.     1
₹ 25,463/sq.ft.      1
₹ 17,857/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 6,289/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 5,093/sq.ft.       1
₹ 8,127/sq.ft.       1
₹ 7,555/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 7,302/sq.ft.       1
₹ 10,484/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 10,591/sq.ft.      1
₹ 24,074/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 30,968/sq.ft.      1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 8,155/sq.ft.       1
₹ 15,437/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 10,067/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 1,560/sq.ft.       1
₹ 20,741/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 20,444/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 28,200/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 14,787/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 6,800/sq.ft.       1
₹ 21,786/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 283,333/sq.ft.     1
₹ 24,573/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 47,803/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 18,605/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 12,198/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 40,000/sq.ft.      1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 17,187/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 10,579/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 28,233/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 29,074/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,645/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 15,384/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 8,947/sq.ft.       1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 11,693/sq.ft.      1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 122,222/sq.ft.     1
₹ 13,542/sq.ft.      1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 20,115/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 16,244/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 86,567/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 7,619/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 33,129/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 1,992/sq.ft.       1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 183,333/sq.ft.     1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 25,543/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 16,003/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 3,254/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 8,796/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 66,666/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 6,567/sq.ft.       1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 35,494/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 23,662/sq.ft.      1
Name: count, dtype: int64

In [ ]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
# bedrooms
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
11 Bedrooms      2
19 Bedrooms      2
18 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [ ]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
62,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
63,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
66,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
67,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
68,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
69,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
70,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
71,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
72,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
73,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
74,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
75,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
76,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
77,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
78,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
83,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,NaN,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
86,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,NaN,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
87,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
88,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
89,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
92,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
93,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
96,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
98,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
99,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
100,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
103,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
104,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
110,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
115,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
273,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
277,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
278,6 Bedroom House for sale in Sector 70 Gurgaon,tulip ivory,NaN,NaN,(697 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 70 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Tulip ivory in sector-70, gurgaon by tulip inf...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
284,3 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf the palm drive,NaN,NaN,(353 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf the palm drive in sector-66, gurgaon...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
292,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(540 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
293,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,14045.0,(363 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
294,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10783.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
295,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10804.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
296,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10783.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
318,3 Bedroom House for sale in Arjun Nagar,independent,NaN,13333.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,2 Bedroom House for sale in Palam Vihar Extension,independent,NaN,6666.0,(49 sq.m.) Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,2 Bedroom House for sale in Rajiv Nagar,independent,NaN,66666.0,(7 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,7 Bedroom House for sale in Surya Vihar,independent,NaN,7500.0,(372 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,2 Bedroom House for sale in Sector 5 Gurgaon,independent,NaN,25000.0,(93 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,4 Bedroom House for sale in Sohna,independent,NaN,6944.0,(167 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,4 Bedroom House for sale in Sector 52 Gurgaon,independent,NaN,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,6 Bedroom House for sale in Sector 22 Gurgaon,saksham welfare association,NaN,19645.0,(220 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(1021, 19)

In [ ]:
df = df[~df["bedRoom"].isnull()]

In [ ]:
df.shape

(964, 19)

In [ ]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
# balcony
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [ ]:
df['balcony'] = df['balcony'].str.split(" ").str.get(0).str.replace("No","0")
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Others                                11
Pooja Room,Store Room                            11
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Servant Room,Pooja Room                           8
Pooja Room,Servant Room,Store Room                7
Servant Room,Pooja Room,Store Room                6
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Study Room,Pooja Room,Servant Room                5
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Servant Room,Store Room                4
Store Room,Pooja Room                             4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Servant Room,Store Room,Pooja Room                4
Pooja Room,Study Room,Others                      4
Pooja Room,Study Room,Store Room                  3
Study Room,Others                                 3
Study Room,Servant Room,Pooja Room                3
Study Room,Pooja Room,Servant Room,Store Room     3
Store Room,Pooja Room,Servant Room                2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Pooja Room,Store Room                  2
Store Room,Pooja Room,Study Room                  2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room,Servant Room     2
Study Room,Pooja Room                             2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Servant Room,Study Room,Store Room,Pooja Room     1
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [ ]:
df['additionalRoom'].fillna('not available',inplace=True)

<ipython-input-65-37c81a970354>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [ ]:
df['additionalRoom'] = df['additionalRoom'].str.lower()
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
# floors
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
10 Floors      2
11 Floors      2
12 Floors      2
21 Floors      1
13 Floors      1
27 Floors      1
02 Floors      1
20 Floors      1
41 Floors      1
51 Floors      1
16 Floors      1
33 Floors      1
Name: count, dtype: int64

In [ ]:
df['noOfFloor'].isnull().sum()

np.int64(19)

In [ ]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [ ]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df['facing'].fillna('NA',inplace=True)
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

<ipython-input-71-2c9d396b7ee7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [ ]:
df.insert(loc=1,column='property_type',value='house')
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df.shape

(964, 20)

In [ ]:
df.to_csv('house_cleaned.csv',index=False)