<a href="https://colab.research.google.com/github/Timansamal046/Real-Estate-Analysys/blob/main/merge_flats_houses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
flats = pd.read_csv('/content/flats_cleaned.csv')
houses = pd.read_csv('/content/house_cleaned.csv')

In [ ]:
df = pd.concat([flats,houses],ignore_index=True)

In [ ]:
df.shape

(3961, 20)

In [ ]:
df = df.sample(df.shape[0],ignore_index=True)
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 109 Gurgaon,flat,ats tourmaline,2.10,8123.0,2585.0,Super Built up area 2585(240.15 sq.m.)Built Up...,3,4,3+,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",11.0,South-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",Check out this 3 bhk flat for sale in ats tour...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,0.89,6339.0,1404.0,Super Built up area 1404(130.44 sq.m.)Carpet a...,2,2,3+,others,"Sector 91 Gurgaon, Gurgaon, Haryana",9.0,East,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",Tarc maceo is one of gurgaon's most sought aft...,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."
2,3 BHK Flat in Sector 77 Gurgaon,flat,emaar palm heights,2.10,10370.0,2025.0,Super Built up area 2025(188.13 sq.m.),3,3,3,"study room,servant room","Sector 77 Gurgaon, Gurgaon, Haryana",17.0,NaN,Within 6 months,"['DLF Cyber City', 'Vatika Town Square', ""St. ...",The flat occupies a super built up area of 202...,"['1 Light', '1 AC', '1 Modular Kitchen', 'No B...","['Lift(s)', 'Park']","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,1.20,8052.0,1490.0,Super Built up area 1490(138.43 sq.m.)Carpet a...,3,3,3,study room,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",9.0,South,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Lower floor unused apartment with park facing ...,"['3 Wardrobe', '5 Fan', '2 Geyser', '7 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
4,3 BHK Flat in Sector 102 Gurgaon,flat,adani m2k oyster grande,1.95,7561.0,2579.0,Super Built up area 2579(239.6 sq.m.),3,4,3,"study room,servant room","B-902, Sector 102 Gurgaon, Gurgaon, Haryana",9.0,South,1 to 5 Year Old,"['WTC Plaza', 'Star Mall', 'Dwarka Expy, Dhanw...",Well maintained appartment....\n \n \n Additio...,"['3 Fan', '1 Exhaust Fan', '1 Geyser', '4 Ligh...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [ ]:
df.to_csv('gurgaon_properties.csv',index=False)